/**
 * Database query functions for The AI Resource Hub.
 * Now reads from Postgres JSON cache (data/pg-cache/*.json) instead of SQLite.
 *
 * The pg-cache files are generated by: node scripts/dump-pg-to-json.mjs
 * This runs as part of the daily pipeline before each build.
 *
 * Original SQLite version preserved at: queries-sqlite.ts
 */

// Re-export everything from the Postgres cache module
export {
  // Models
  getLLMModelsFromDB,
  getModelsByCategory,
  getModelById,
  getAllModelIds,
  getRecentModels,
  getModelsByProvider,
  getModelsByProviderGrouped,
  getModelCounts,
  getModelsWithTTFT,

  // Providers
  getProviders,
  getProviderById,
  getAllProviderIds,
  getProvidersWithCounts,

  // Benchmarks
  getBenchmarks,
  getBenchmarkById,
  getAllBenchmarkIds,
  getBenchmarkScores,
  getModelBenchmarks,
  getScoresForBenchmark,
  getBenchmarkMatrix,

  // People
  getPeople,
  getPeopleByProvider,

  // News (now from shared pipeline, not Hub RSS)
  getNews,
  getNewsByCategory,
  getNewsCategories,

  // Price history
  getPriceHistory,
  getModelPriceHistory,
  getModelsWithPriceHistory,

  // Scrape log
  getLastScrapeTime,

  // Stubs for tables not yet migrated or empty
  getGlossaryTerms,
  getGlossaryTermById,
  getAllGlossaryIds,
  getYouTubeCreators,
  getYouTubeCreatorsByCategory,
  getYouTubeCreatorCategories,
  getTags,
  getTagById,
  getAllTagIds,
  getTagsForItem,
  getItemsByTag,
  getTagsWithCounts,
  getRumouredModels,
  getCLITools,
  getCLIToolById,
  getAllCLIToolIds,
  getProviderPlans,
  getModelMessageLimits,
  getPlanLimits,
  getAllSubscriptionPlans,
  getProviderEndpoints,
  getModelsWithMultipleEndpoints,
} from './pg-cache';

// ─── Type exports (preserved for Astro page compatibility) ─────

export interface DBProvider {
  id: string;
  name: string;
  colour: string;
  website: string | null;
  status_url?: string | null;
  api_docs_url?: string | null;
  description: string | null;
  founded: string | null;
  headquarters: string | null;
  ceo: string | null;
  funding: string | null;
}

export interface DBBenchmark {
  id: string;
  name: string;
  category: string;
  description: string | null;
  url: string | null;
  scale_min: number;
  scale_max: number;
  higher_is_better: number | boolean;
  weight: number;
}

export interface DBBenchmarkScore {
  model_id: string;
  benchmark_id: string;
  benchmark_name: string;
  score: number;
  source: string | null;
}

export interface DBPerson {
  id: string;
  name: string;
  role: string | null;
  organisation: string | null;
  provider_id: string | null;
  bio: string | null;
  twitter: string | null;
  website: string | null;
  notable_for: string | null;
}

export interface BenchmarkMatrix {
  benchmarks: DBBenchmark[];
  models: Array<{
    id: string;
    name: string;
    provider: string;
    providerColour: string;
    scores: Record<string, number>;
  }>;
}

export interface DBModelDetail {
  id: string;
  name: string;
  provider_id: string;
  provider_name: string;
  provider_colour: string;
  provider_website: string | null;
  input_price: number;
  output_price: number;
  context_window: number;
  max_output: number;
  speed: number;
  ttft: number;
  speed_source: string | null;
  speed_updated: string | null;
  quality_score: number;
  released: string | null;
  open_source: number | boolean;
  modality: string;
  api_available: number | boolean;
  notes: string | null;
  category: string;
  pricing_source: string | null;
  pricing_updated: string | null;
}

export interface DBPriceHistory {
  input_price: number;
  output_price: number;
  recorded_at: string;
  source: string | null;
}

export interface PriceHistoryWithModel {
  model_id: string;
  model_name: string;
  provider: string;
  provider_colour: string;
  input_price: number;
  output_price: number;
  recorded_at: string;
}

export interface DBProviderEndpoint {
  id: string;
  model_id: string;
  provider_id: string;
  provider_name: string;
  provider_colour: string;
  endpoint_name: string;
  speed: number;
  ttft: number;
  input_price: number;
  output_price: number;
  measured_at: string | null;
  source: string | null;
}

export interface DBModelTTFT {
  id: string;
  name: string;
  ttft: number;
  speed: number;
  provider: string;
  provider_colour: string;
  quality_score: number;
  input_price: number;
  output_price: number;
  speed_source: string | null;
}

export interface DBRumouredModel {
  id: string;
  codename: string;
  provider_id: string | null;
  provider_name: string | null;
  provider_colour: string | null;
  status: string;
  first_seen: string;
  confirmed_as: string | null;
  confirmed_name: string | null;
  sources: string | null;
  notes: string | null;
  category: string;
}

export interface DBGlossaryTerm {
  id: string;
  term: string;
  definition: string;
  plain_english: string | null;
  category: string;
  related_terms: string | null;
  see_also: string | null;
}

export interface CategoryModel {
  id: string;
  name: string;
  provider: string;
  providerColour: string;
  inputPrice: number;
  outputPrice: number;
  contextWindow: number;
  maxOutput: number;
  speed: number;
  qualityScore: number;
  released: string;
  openSource: boolean;
  modality: string;
  apiAvailable: boolean;
  notes: string | undefined;
}

export interface DBYouTubeCreator {
  id: string;
  name: string;
  channel_name: string;
  youtube_handle: string | null;
  subscribers: number;
  category: string;
  description: string | null;
  twitter: string | null;
  website: string | null;
  person_id: string | null;
}

export interface DBTag {
  id: string;
  name: string;
  category: string;
  description: string | null;
}

export interface DBNews {
  id: string;
  title: string;
  url: string;
  source: string;
  summary: string | null;
  image_url?: string | null;
  published_at: string;
  category: string;
}

export interface BenchmarkDetail {
  id: string;
  name: string;
  category: string;
  description: string | null;
  url: string | null;
  scale_min: number;
  scale_max: number;
  higher_is_better: number | boolean;
  weight: number;
}

export interface BenchmarkModelScore {
  model_id: string;
  model_name: string;
  provider: string;
  provider_id: string;
  providerColour: string;
  score: number;
  source: string | null;
  source_url: string | null;
  measured_at: string | null;
  category: string;
}

export interface RecentModel {
  id: string;
  name: string;
  provider: string;
  providerColour: string;
  category: string;
  released: string | null;
  qualityScore: number;
}

export interface DBSubscriptionPlan {
  id: string;
  provider_id: string;
  plan_name: string;
  price_monthly: number | null;
  price_yearly_monthly: number | null;
  tier_level: number;
  source_url: string | null;
  notes: string | null;
}

export interface DBPlanModelLimit {
  plan_id: string;
  plan_name: string;
  price_monthly: number | null;
  model_id: string | null;
  model_tier: string | null;
  model_name: string | null;
  messages_low: number | null;
  messages_high: number | null;
  message_period: string;
  notes: string | null;
}

export interface DBCLITool {
  id: string;
  name: string;
  provider_id: string | null;
  provider_name: string | null;
  provider_colour: string | null;
  maker: string;
  description: string | null;
  default_model: string | null;
  supported_models: string | null;
  context_window: number;
  open_source: number | boolean;
  license: string | null;
  github_url: string | null;
  website: string | null;
  install_command: string | null;
  pricing_type: string;
  pricing_note: string | null;
  mcp_support: number | boolean;
  multi_file: number | boolean;
  git_integration: number | boolean;
  platforms: string;
  released: string | null;
  status: string;
  notes: string | null;
}

// ─── Jobs (new from Codex) ──────────────────────────────────────

import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const CACHE_DIR = path.join(process.cwd(), 'data', 'pg-cache');

function loadJobsCache<T>(name: string): T[] {
  const filePath = path.join(CACHE_DIR, `${name}.json`);
  if (!existsSync(filePath)) return [];
  return JSON.parse(readFileSync(filePath, 'utf8')) as T[];
}

export interface AIJobsOverview {
  total_open_roles: number;
  posted_last_14d: number;
  posted_last_30d: number;
  dated_roles: number;
  companies: number;
}

export function getAIJobsOverview(): AIJobsOverview {
  const jobs = loadJobsCache<{ posted_at: string | null; active: boolean }>('ai_jobs');
  const companies = loadJobsCache<{ id: string }>('job_companies');
  const now = Date.now();
  const d14 = 14 * 24 * 60 * 60 * 1000;
  const d30 = 30 * 24 * 60 * 60 * 1000;

  let posted14 = 0, posted30 = 0, dated = 0;
  for (const j of jobs) {
    if (j.posted_at) {
      dated++;
      const age = now - new Date(j.posted_at).getTime();
      if (age < d14) posted14++;
      if (age < d30) posted30++;
    }
  }

  return {
    total_open_roles: jobs.length,
    posted_last_14d: posted14,
    posted_last_30d: posted30,
    dated_roles: dated,
    companies: companies.length,
  };
}

export function getAIJobs() {
  return loadJobsCache('ai_jobs');
}

export function getJobCompanies() {
  return loadJobsCache('job_companies');
}

export function getJobSnapshots() {
  return loadJobsCache('ai_job_snapshots');
}
